---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify_topic(classify_topic)
	check_rag(check_rag)
	rag_retrieval(rag_retrieval)
	web_search(web_search)
	generate_explanation(generate_explanation)
	assess_quality(assess_quality)
	rewrite_explanation(rewrite_explanation)
	verify_understanding(verify_understanding)
	reflect_on_learning(reflect_on_learning)
	assess_comprehension(assess_comprehension)
	build_on_understanding(build_on_understanding)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify_topic;
	assess_comprehension --> build_on_understanding;
	assess_quality -.-> rewrite_explanation;
	assess_quality -.-> verify_understanding;
	build_on_understanding --> finalize;
	check_rag -.-> rag_retrieval;
	check_rag -.-> web_search;
	classify_topic -.-> assess_comprehension;
	classify_topic -.-> check_rag;
	generate_explanation -.-> assess_quality;
	generate_explanation -.-> finalize;
	rag_retrieval --> web_search;
	reflect_on_learning --> finalize;
	rewrite_explanation --> generate_explanation;
	verify_understanding -.-> finalize;
	verify_understanding -.-> reflect_on_learning;
	web_search --> generate_explanation;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
