"""Mark ticker for charting (actual chart generated by UI layer)."""

from derivatives_gpt_core.agents.shared.base_state import BaseAgentState
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


def generate_ticker_chart(state: BaseAgentState) -> Dict[str, Any]:
    """
    Mark ticker for charting.

    CRITICAL RULE: TICKER RECOGNIZED = CHARTING HAPPENS

    This node sets a flag that tells the UI layer to generate and display the chart.
    We don't generate the chart here because Plotly figures are not msgpack serializable
    and can't be stored in the checkpointer.

    The chainlit launcher will see chart_generated=True and create the chart directly.

    Args:
        state: State with extracted ticker

    Returns:
        dict: Updated state with chart_generated flag

    Edge cases:
    - No ticker: Skip charting silently
    """
    ticker = state.ticker or state.extracted_ticker

    # Skip if no ticker
    if not ticker:
        logger.info("No ticker found, skipping chart generation")
        return {"chart_generated": False}

    logger.info(f"CHARTING FIRST: Marking {ticker} for chart generation")
    return {"chart_generated": True}
